name: build macOS installer

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App name (e.g., Installer, WillowKickSnareInstaller, ChiodosDrumkitInstaller)'
        required: false
        default: 'Installer'

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build .app with PyInstaller (GUI)
        run: |
          APP_NAME="${{ github.event.inputs.app_name }}"
          pyinstaller installer_v2.py \
            --name "$APP_NAME" \
            --windowed --clean \
            --collect-data customtkinter \
            --collect-submodules Crypto

      - name: Create DMG
        run: |
          brew install create-dmg || true
          create-dmg --overwrite \
            --dmg-title "${{ github.event.inputs.app_name }}" \
            "dist/${{ github.event.inputs.app_name }}.app" \
            "dist/${{ github.event.inputs.app_name }}.dmg"

      # OPTIONAL: Code sign + notarize (requires secrets below)
      # - name: Import signing cert
      #   uses: apple-actions/import-codesign-certs@v2
      #   with:
      #     p12-file-base64: ${{ secrets.MACOS_CERT_P12 }}
      #     p12-password: ${{ secrets.MACOS_CERT_PASSWORD }}
      #
      # - name: Codesign .app and DMG
      #   run: |
      #     IDENTITY="${{ secrets.MACOS_CODESIGN_IDENTITY }}" # e.g. "Developer ID Application: Your Name (TEAMID)"
      #     /usr/bin/codesign --deep --force --options runtime --sign "$IDENTITY" "dist/${{ github.event.inputs.app_name }}.app"
      #     /usr/bin/codesign --force --sign "$IDENTITY" "dist/${{ github.event.inputs.app_name }}.dmg"
      #
      # - name: Notarize (App Store Connect API key)
      #   run: |
      #     echo "${{ secrets.AC_API_KEY_P8 }}" > authkey.p8
      #     xcrun notarytool submit "dist/${{ github.event.inputs.app_name }}.dmg" \
      #       --key authkey.p8 \
      #       --key-id "${{ secrets.AC_API_KEY_ID }}" \
      #       --issuer "${{ secrets.AC_API_ISSUER_ID }}" \
      #       --wait
      #     xcrun stapler staple "dist/${{ github.event.inputs.app_name }}.dmg"

      - name: Upload artifact (DMG)
        uses: actions/upload-artifact@v4
        with:
          name: mac-installer-${{ github.event.inputs.app_name }}
          path: dist/${{ github.event.inputs.app_name }}.dmg
