name: macOS DMG MOUNT

on:
  workflow_dispatch:
    inputs:
      dmg_url:
        description: "Public or signed URL to the DMG (e.g., https://storage.googleapis.com/<BUCKET>/<OBJECT>.dmg)"
        required: true
      sha256:
        description: "Optional expected SHA256 checksum of the DMG"
        required: false

jobs:
  smoke:
    runs-on: macos-14
    env:
      MOUNTPOINT: /Volumes/WKSTest
      DMG_PATH: WillowKickSnareInstaller.dmg

    steps:
      - name: Show macOS version
        run: sw_vers

      - name: Download DMG
        run: |
          curl -L --fail --output "$DMG_PATH" "${{ github.event.inputs.dmg_url }}"
          ls -la "$DMG_PATH"

      - name: Verify SHA256 (optional)
        if: ${{ inputs.sha256 != '' }}
        run: echo "${{ github.event.inputs.sha256 }}  $DMG_PATH" | shasum -a 256 -c -

      - name: Mount DMG (read-only, no Finder)
        run: hdiutil attach "$DMG_PATH" -mountpoint "$MOUNTPOINT" -nobrowse -readonly

      - name: List mounted volume
        run: ls -la "$MOUNTPOINT"

      - name: Locate .app or .pkg inside DMG
        id: locate
        run: |
          set -euo pipefail
          PAYLOAD="$(/usr/bin/find "$MOUNTPOINT" -maxdepth 3 \( -name "*.app" -o -name "*.pkg" \) -print -quit)"
          if [ -z "$PAYLOAD" ]; then
            echo "No .app or .pkg found inside $MOUNTPOINT"
            exit 1
          fi
          echo "Found payload: $PAYLOAD"
          if [[ "$PAYLOAD" == *.pkg ]]; then
            echo "spctl_type=install" >> "$GITHUB_OUTPUT"
            echo "payload_ext=pkg" >> "$GITHUB_OUTPUT"
          else
            echo "spctl_type=execute" >> "$GITHUB_OUTPUT"
            echo "payload_ext=app" >> "$GITHUB_OUTPUT"
          fi
          printf 'payload=%s\n' "$PAYLOAD" >> "$GITHUB_OUTPUT"

      - name: Gatekeeper assessment
        run: spctl --assess --type "${{ steps.locate.outputs.spctl_type }}" -v "${{ steps.locate.outputs.payload }}" || true

      - name: Check quarantine flags (apps only)
        if: ${{ steps.locate.outputs.payload_ext == 'app' }}
        run: xattr -l "${{ steps.locate.outputs.payload }}" || true

      - name: Verify code signature (apps only)
        if: ${{ steps.locate.outputs.payload_ext == 'app' }}
        run: codesign --verify --deep --strict "${{ steps.locate.outputs.payload }}" || true

      - name: Unmount DMG
        if: always()
        run: hdiutil detach "$MOUNTPOINT" || true
